### ISSUE TITLE
Generte documentation for variables exposed with __all__

### ISSUE THREAD

**Issue by thrau** [mitmproxy/pdoc#409] opened 2022-07-01 19:03 UTC
#### Problem Description

I have a module, say `myproject/_internal.py`, that has a variable doc:
```python
# myproject/_internal.py

my_variable = "foobar"
"""Here's the variable doc"""
```

And i expose this via `__all__` through `myproject/api/variables.py`:
```python
# myproject/api/variables.py

from myproject._internal import my_variable

__all__ = [
    "my_variable"
]
```

Then when I generate the doc for `myproject.api`, I would expect the docs to contain the variable docs, but it doesn't. 

#### Steps to reproduce the behavior:
1. Create the modules as described above
2. run `pdoc --html -o docs myproject.api`
3. open `docs/myproject/api/index.html`

#### System Information

```
 % pdoc --version
pdoc 0.10.0

 % python --version                                                    
Python 3.10.4
```

Thanks for the awesome tool :-)

**Comment by mhils** [comment] 2022-07-03 20:38
> ```
>  % pdoc --version
> pdoc 0.10.0
> ```

You are presumably using pdoc3 and not pdoc, which likes to hijack this project's name. See https://github.com/mitmproxy/pdoc#pdoc-vs-pdoc3. :(

Apart from this, this would be a duplicate of #365. :)

**Closed by mhils** 2022-07-03 20:38 UTC
Labels: bug

**Comment by thrau** [comment] 2022-07-03 23:00
thanks for the clarification
