### ISSUE TITLE
Pydantic >=2.9 class won't render on Windows

### ISSUE THREAD

**Issue by elliot-100** [mitmproxy/pdoc#741] opened 2024-09-16 20:41 UTC
#### Problem Description

Pydoc will render a Pydantic < 2.9 class, but not a Pydantic >=2.9 class.
I assume it's a Pydantic issue, but I thought I'd let you know.

#### Steps to reproduce the behavior:
1. Create a trivial Pydantic class, e.g `example.py` with Pydantic 2.8.2 (latest 2.8.x version) installed:
```
from pydantic import BaseModel

class MyModel(BaseModel):
    uid: int
```
2. `pdoc .\example.py` renders OK
3.  Update Pydantic to 2.9.0 or 2.9.1 (latest)
4. `pdoc .\example.py` gives:

```
Error importing 'example'
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\pdoc-issue-6Ujrf-gf-py3.12\Lib\site-packages\pdoc\doc_types.py", line 102, in safe_eval_type
    return _eval_type(t, globalns, localns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\pdoc-issue-6Ujrf-gf-py3.12\Lib\site-packages\pdoc\doc_types.py", line 212, in _eval_type
    (type_,) = (eval(t.__forward_code__, globalns, localns),)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
TypeError: 'function' object is not subscriptable
...[snipped]...
File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\pdoc-issue-6Ujrf-gf-py3.12\Lib\site-packages\pdoc\doc_types.py", line 123, in safe_eval_type
    warnings.warn(f"Error parsing type annotation {t} for {fullname}: {e}")
UserWarning: Error parsing type annotation dict[str, Any] | None for pydantic.main.BaseModel.__pydantic_extra__: 'function' object is not subscriptable



#### System Information
Paste the output of "pdoc --version" here.
```
pdoc: 14.7.0
Python: 3.12.6
Platform: Windows-11-10.0.22631-SP0
```

**Comment by mhils** [comment] 2024-09-16 21:23
Thank for the report. I do get warnings, but I can't reproduce a crash:
```
λ cat repro.py
from pydantic import BaseModel

class MyModel(BaseModel):
    uid: int

(venv) ~/g/pdoc
λ pip freeze | rg pydantic
pydantic==2.9.1
pydantic_core==2.23.3
(venv) ~/g/pdoc
λ pdoc --version
pdoc: 14.7.0 (+4, commit b5963c5)
Python: 3.12.4
Platform: Linux-4.4.0-22621-Microsoft-x86_64-with-glibc2.35
(venv) ~/g/pdoc
λ pdoc -o .render repro.py
Warn: Error parsing type annotation dict[str, Any] | None for pydantic.main.BaseModel.__pydantic_extra__: 'function' object is not subscriptable (/mnt/c/Users/user/git/pdoc/pdoc/doc_types.py:123)
Warn: Error parsing type annotation dict[str, Any] | None for pydantic.main.BaseModel.__pydantic_private__: 'function' object is not subscriptable (/mnt/c/Users/user/git/pdoc/pdoc/doc_types.py:123)
```

**Comment by elliot-100** [comment] 2024-09-17 14:27
I also get warnings rather than crash on Ubuntu Linux, so am assuming Windows issue only.

**Comment by mhils** [comment] 2024-09-17 18:39
I cannot reproduce this on Windows either:
```
> pdoc --version
pdoc: 14.7.0 (+4, commit b5963c5)
Python: 3.12.0
Platform: Windows-11-10.0.22631-SP0
```

**Comment by elliot-100** [comment] 2024-09-19 15:36
Hmmm. I doubt I will have time to investigate further. It's fine if you would like to close.

**Comment by mhils** [comment] 2024-09-19 17:32
Closing this until someone has a reproducer :)

**Closed by mhils** 2024-09-19 17:32 UTC
Labels: bug

**Comment by elliot-100** [comment] 2024-10-11 14:49
Just realised this was down to my environment - I had env var `PYTHONWARNINGS: error::UserWarning` set, effectively converting those warnings into errors. Oops!
