### ISSUE TITLE
Error: no attribute 'signature_without_self'

### ISSUE THREAD

**Issue by ekwan** [mitmproxy/pdoc#519] opened 2023-03-07 14:57 UTC
#### Problem Description
Hi!  I'm getting an error: 

**jinja2.exceptions.UndefinedError: 'pdoc.doc.Module object' has no attribute 'signature_without_self'**

Any idea what it could be?

Here's the full trace:

Traceback (most recent call last):
  File "/Users/kwaneu/miniconda3/envs/obsidian/bin/pdoc", line 8, in <module>
    sys.exit(cli())
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/site-packages/pdoc/__main__.py", line 185, in cli
    pdoc.pdoc(
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/site-packages/pdoc/__init__.py", line 513, in pdoc
    search = render.search_index(all_modules)
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/site-packages/pdoc/render.py", line 147, in search_index
    index = make_index(
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/site-packages/pdoc/search.py", line 116, in make_index
    documents.extend(make_index(module))
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/site-packages/pdoc/search.py", line 86, in make_index
    if not is_public(mod):
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/site-packages/pdoc/render.py", line 145, in is_public
    return bool(ctx["is_public"](x).strip())
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/site-packages/jinja2/runtime.py", line 763, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/site-packages/pdoc/templates/default/module.html.jinja2", line 783, in macro
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/Users/kwaneu/miniconda3/envs/obsidian/lib/python3.10/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
**jinja2.exceptions.UndefinedError: 'pdoc.doc.Module object' has no attribute 'signature_without_self'**

#### Steps to reproduce the behavior:
`pdoc -o docs obsidian/*.py obsidian/benchmarks/*.py obsidian/models/*.py`

#### System Information
pdoc: 13.0.0
Python: 3.10.9
Platform: macOS-10.16-x86_64-i386-64bit

**Comment by mhils** [comment] 2023-03-07 15:05
Can you please provide self-contained steps to reproduce this? Where can I find obsidian?

**Comment by lorenzoconti** [comment] 2023-03-21 09:49
I had the same issue with version 13.0.0. I downgraded to 12.3.1 and now it works fine. 

I'm running the following command
`pdoc -o ./docs -d google <package-name>`

Unfortunately I can't share the package, but maybe can help @ekwan

**Comment by mhils** [comment] 2023-03-21 09:54
I've tried quite a bit to reproduce this, but no dice - we need some reproducer here to understand what's going on. I'm happy to handle examples confidentially if you can send them by email.

**Comment by mhils** [comment] 2023-03-21 18:10
Someone volunteered their codebase, this will be fixed with https://github.com/mitmproxy/pdoc/pull/522! :)

**Comment by mhils** [comment] 2023-03-21 18:21
From email:

> Cool, would you mind sharing what the problem was on the Issue page so we can all learn?  Thanks!

The root cause here was that an invocation like `pdoc ./foo/__init__.py` would cause pdoc to treat `foo.__init__` as the module to document, as opposed to just `foo`. That's fixed [here](https://github.com/mitmproxy/pdoc/pull/522/files#diff-d61dde92ade65331d480bebd3969a998ab12c7dfc8e02c36e2c9b27a78c0cc2cR133).

This bug also exists in previous releases, but came to light in 13.0.0 because there we incorrectly assumed that something named `__init__` is a function (which would have a `signature_without_self` attribute). That's wrong as well, so I've also added a guard to that [here](https://github.com/mitmproxy/pdoc/pull/522/files#diff-c68875945a34ceeaf740ec189b56e985d7832f102624add373ce897f798652ebR241) and a test [here](https://github.com/mitmproxy/pdoc/pull/522/files#diff-16e5f13cf7c5f60f18f24e290d23c46a339dead26465af4516729ae766559607R401).

**Closed** 2023-03-21 18:24 UTC
Labels: bug
