### ISSUE TITLE
Can not generate documentation

### ISSUE THREAD

**Issue by scotthuang1989** [mitmproxy/pdoc#233] opened 2021-03-17 16:21 UTC
Here is my experiments:

1. Download pdoc source code.
2. run this command:  `pdoc -o ./html pdoc`
3. pdoc will generate documentaion for all modules.
4. Create a md_test.py under folder pdoc/markdown2. It's content is:
`"""
This is a test documentaion
"""`
5. run  `pdoc -o ./html pdoc` again (before run it , delete all html folder)
6. NO documentation generated for md_test.py

How can I generate documentation for md_test.py?

**Comment by mhils** [comment] 2021-03-17 16:23
How did you install pdoc? Did you run `pip install .`, `pip install pdoc`, or `pip install -e .`?

**Comment by scotthuang1989** [comment] 2021-03-17 16:25
pip install pdoc. my python and pip is from anaconda, my operation system is ubuntu 18.04

**Comment by mhils** [comment] 2021-03-17 16:32
Thanks! So what I suspect is happening here is that you have two "pdoc"s: First, the pdoc you installed using `pip install` (stored in your Python installation's site-packages directory) and the one you downloaded. If you run `pdoc -o ./html pdoc`, it will document the pdoc version you installed. 

I suspect you should see your md_test file if you run `pdoc -o ./html ./pdoc`, which makes it clear that you want to document the downloaded version instead. Can you confirm that?

**Comment by mhils** [comment] 2021-03-19 13:37
Hey there! I believe this is fixed with 6.4.1 (see my previous comment). If that's not the case, please reopen. 😃

**Closed by mhils** 2021-03-19 13:37 UTC

**Comment by scotthuang1989** [comment] 2021-03-20 02:28
@mhils  I upgrade pdoc to 6.4.1 and run `pdoc -o ./html ./pdoc`, still have same problem. 
But, I run pdoc on my own project, it works fine.

**Comment by mhils** [comment] 2021-03-20 11:09
Thanks @scotthuang1989! I have taken another look and can now reproduce your issue. The problem here is that pdoc cannot import a folder named pdoc because that conflict's with pdoc's own Python module. Once #237 is merged we should have a prominent warning for this case. 😃
