### ISSUE TITLE
Instance variables set using __pdoc__ don't work

### ISSUE THREAD

**Issue by JPLeBreton** [mitmproxy/pdoc#107] opened 2016-05-27 15:31 UTC
If I have something like:

``` python
class Foo:
    a,b,c = 0, 1, 2
    def __init__(self):
        self.d, self.e, self.f = 3, 4, 5
```

Class variables a,b,c show up in the generated docs, but instance variables d,e,f do not.
Expected result: instance variables declared in this manner should show up in generated docs.

**Comment by BurntSushi** [comment] 2016-05-27 15:51
Instance variables are detected by parsing the AST. I'd prefer a lower tech solution. You must write each instance variable on its own line, or modify `__pdoc__` directly.

**Comment by JPLeBreton** [comment] 2016-06-01 15:52
Okay, thanks. I'm trying to work out how to do that; nothing I try is working. From the example above, would I do this?
```python
__pdoc__ = {}
__pdoc__['Foo.d'] = "Docstring for Foo's d instance variable."
class Foo:
    a,b,c = 0, 1, 2
    def __init__(self):
        self.d, self.e, self.f = 3, 4, 5
```
or `__pdoc__['mymodule.Foo.d']`? or something else?

**Comment by BurntSushi** [comment] 2016-06-01 16:12
[From the docs](http://pdoc.burntsushi.net/pdoc):

> Thirdly and finally, docstrings can be overrided with a special __pdoc__ dictionary that pdoc inspects if it exists. The keys of __pdoc__ should be identifiers within the scope of the module. (In the case of an instance variable self.variable for class A, its module identifier would be A.variable.) The values of __pdoc__ should be docstrings.

So `Foo.d` should work.

It looks like your example doesn't work, which means this is probably a bug. It looks like putting each instance variable on its own line does work though.

**Comment by JPLeBreton** [comment] 2016-06-01 19:53
Thanks. Shall I file a bug for that related-but-separate issue?

**Comment by BurntSushi** [comment] 2016-06-02 12:58
This issue is fine. I renamed the title. I don't think I'll ever support multiple instance variables defined on the same line.

**Comment by DewaldDeJager** [comment] 2017-04-30 16:28
+1 for adding support for multiple instance variables defined on the same line. Wanted to see if there wasn't an issue on this already before opening one. My use case:

```python
(self.var1, self.var2, self.var3) = self.method_that_returns_tuple()
```

Hopefully in future I can get some time and submit a pull request with this added. Thanks for the great tool, Andrew!

**Comment by mhils** [comment] 2021-01-19 16:22
Hi, current pdoc maintainer here! The recommended workaround to do this now is to document your variables on the class itself, see
https://pdoc.dev/docs/pdoc.html#document-variables.

I'll close this here as we have (at least temporarily) removed `__pdoc__`.

**Closed by mhils** 2021-01-19 16:22 UTC

**Comment by daniele-niero** [comment] 2022-11-10 16:23
Is there any way, template, macros, whatever, to force **any** instance variable to show up in the documentation regardless their docstring status?

Sometimes this variables don't need any explanation but having them in the documentation is needed to give the users all the clear information they need

A very simple example that come to mind is a Vector class
```python
class Vector:
    def __init__(self):
        self.x = 0.0
        self.y = 0.0
        self.z = 0.0
```
Now x, y and z won't appear in the documentation, unless I document them. But should I really have to document them? and with what? 
```python
class Vector:
    def __init__(self):
        self.x = 0.0
        """ The vector's x component"""
        self.y = 0.0
        """ The vector's y component"""
        self.z = 0.0
        """ The vector's z component"""
```
In my opinion It is kind of redundant.

**Comment by mhils** [comment] 2022-11-10 16:27
You can write a template that overrides `is_public`, see for example https://github.com/mitmproxy/pdoc/blob/main/examples/custom-template/module.html.jinja2.

Specifically:
```jinja2
{% macro is_public(doc) %}
    {% if doc.kind == "variable" %}
        true
    {% else %}
        {{ default_is_public(doc) }}
    {% endif %}
{% endmacro %}
```

**Comment by daniele-niero** [comment] 2022-11-11 09:42
This doesn't work, the problem is that instance or class variables seems not being picked up by pdoc's api at all, unless they are commented, so the never get passed to that macro in the first place.

I tried and they are not included in what is returned by methods such as `member`, `own_members` etc.

And as a small note, they are public in my example, so is not really that the issue. They should be picked up like any other member. A method, for instance, even if not documented, ends up in the documentation

**Comment by mhils** [comment] 2022-11-11 14:54
True - we didn't pick them up so far as they are excluded in the default template. https://github.com/mitmproxy/pdoc/pull/461 fixes this!

**Comment by daniele-niero** [comment] 2022-11-14 14:20
Thank you, works like a charm :)
