### ISSUE TITLE
Info about submodules is not being displayed as markdown

### ISSUE THREAD

**Issue by nbro** [mitmproxy/pdoc#125] opened 2017-02-19 17:10 UTC
Look for example at this result:

<img width="1354" alt="no-markdown" src="https://cloud.githubusercontent.com/assets/9349000/23104441/63862188-f6ce-11e6-89bb-ed4413f5b938.png">

even though inside the module the result is as expected

<img width="1342" alt="ok" src="https://cloud.githubusercontent.com/assets/9349000/23104458/979442a2-f6ce-11e6-9d06-4afe7987e0b9.png">

but it would be nice that the external part is also markdown, or it's better not to have that initial introduction at all. Is this bug?

**Comment by BurntSushi** [comment] 2017-02-19 17:12
I don't see the problem. Module documentation is rendered as markdown. If the docs aren't formatted as markdown, then it won't render how you want.

It's pretty hard to say anything more without seeing the input.

**Comment by nbro** [comment] 2017-02-19 17:24
@BurntSushi `ands.algorithms.ode` is just a folder with a `__init__.py` file, which contains just comments saying that it's required to consider the folder `ode` a Python package in the versions previously to Python 3.3. 

That info, which is not markdown, is automatically displayed, I guess, by `pdoc` by gathering it from the module `forward_euler.py`. The docstrings in `forward_euler.py` are indeed markdown.

If you want to see the project: [https://github.com/nbro/ands/tree/master/ands/algorithms/ode](https://github.com/nbro/ands/tree/master/ands/algorithms/ode). I've also created a script (under the folder `scripts` of the root folder of the project) that uses `pdoc` to generate the documentation, if you want to use it.

**Comment by BurntSushi** [comment] 2017-02-19 17:30
I don't understand what you expect to happen. `pdoc` can't magically turn a non-Markdown docstring into a Markdown string.

**Comment by nbro** [comment] 2017-02-19 17:37
@BurntSushi Those strings are Markdown! The info that I'm claiming is displayed not in Markdown, that is:

<img width="1354" alt="not-markdown" src="https://cloud.githubusercontent.com/assets/9349000/23104642/4c6bd1f6-f6d2-11e6-9996-54dfd1760327.png">

are actually Markdown strings, as you can see from the source code (that I linked you to):

```

"""
# Meta info

Author: Nelson Brochado

Created: 10/09/2016

Updated: 19/02/2017

# Description

The forward Euler's method for solving ODEs is the easiest method
for approximately solving a _initial value_ ODE problem.
Hence it's used, in general, as a vehicle for studying
several important and basic notions on numerical ODE methods.

```

As you can see, Github displays them correctly here, in this comment!

**Comment by BurntSushi** [comment] 2017-02-19 17:40
@nbro Interesting. Not sure what the problem is. I'd check the markdown template to see if there's anything fish with showing the docs for submodules.

**Comment by mhils** [comment] 2021-01-19 16:19
Thanks for reporting and sorry for the slow turnaround time. This should be fixed with the latest release. 😃

**Closed by mhils** 2021-01-19 16:19 UTC
