### ISSUE TITLE
Class data members are included in the documentation when the type is explicitly defined.

### ISSUE THREAD

**Issue by ravenexp** [mitmproxy/pdoc#280] opened 2021-07-07 09:27 UTC
#### Problem Description

As I understand it, pdoc does not document the class data members by default.
But, when the data member type is specified explicitly in `__init__()`, pdoc documents it by default.

#### Steps to reproduce the behavior:

```python
class Foo:
    def __init__(self) -> None:
        """
        Foo() constructor
        """

        self.a = 0
        self.b: int = 0
```

Data member `a` is not included in the `Foo` class documentation, but data member `b` is.

#### System Information

```
pdoc: 7.1.1
Python: 3.9.6
Platform: Linux-5.12.14-arch1-1-x86_64-with-glibc2.33
```

**Comment by mhils** [comment] 2021-07-15 11:57
Hi there!

This is more or less expected behavior. pdoc documents all attributes that have either a docstring or a type annotation. We don't document members for which neither is present, mostly because there's really not much to document. If you want members to not be public, I'd recommend you prefix them with an underscore, which is a more general Python convention. Does that make sense?

**Comment by ravenexp** [comment] 2021-07-15 18:15
Probably. I wasn't prefixing the data members with underscores (as I should have been), but I also use type annotations everywhere. It didn't bother me at all because the type of the data members was correctly inferred in 99% of cases. But then I needed something like `foo: Optional[Foo] = None` and it stood out like a sore thumb...

**Comment by mhils** [comment] 2021-07-15 18:24
By "I also use type annotations everywhere", you mean everywhere but for attributes/data members?

I guess I do have some sympathy for your use case. A reasonable change here would be to only add variables with docstrings instead of adding variables that have a docstring, an annotation, or both. I think it should be enough to remove those four lines:

https://github.com/mitmproxy/pdoc/blob/fdb6fdeb6dc1a91134aa17bd715c877bfc775867/pdoc/doc.py#L583-L584

https://github.com/mitmproxy/pdoc/blob/fdb6fdeb6dc1a91134aa17bd715c877bfc775867/pdoc/doc.py#L475-L476

I feel both approaches are valid, maybe other folks want to chime in. :)

**Comment by ravenexp** [comment] 2021-07-15 18:37
> By "I also use type annotations everywhere", you mean everywhere but for attributes/data members?

There's no need, because the data members are typically defined like

```python
def __init__(self):
    ...
    self.foo = Foo()
    ...
```

where the `foo` data type is automatically inferred from the RHS of the assignment.

**Comment by mhils** [comment] 2021-07-28 14:32
You've convinced me here, this will be fixed with the next release!

**Closed** 2021-07-28 14:31 UTC
Labels: bug
